# Generated by Django 3.2.9 on 2022-09-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('count', models.IntegerField(default=1, verbose_name='졸음 횟수')),
                ('date', models.DateTimeField(verbose_name='졸음 발생 시간')),
            ],
        ),
    ]
